- name: install | Downloading code-server
  get_url:
    url: "{{ code_server_dl_url + '/' + code_server_bin + '.tar.gz'  }}"
    dest: /tmp
  become: true

- name: install | Extracting code-server package
  unarchive:
    src: "{{ '/tmp/' + code_server_bin + '.tar.gz'}}"
    dest: /tmp
    remote_src: true
  become: true

- name: Copy files to bin
  copy: remote_src=True src="{{ '/tmp/'+ code_server_bin +'/code-server' }}" dest=/bin/code-server
  become: true

- name: Clear /tmp
  file:
    state: absent
    path: "{{ item  }}"
  with_items:
    - "{{'/tmp/'+code_server_bin}}"
    - "{{'/tmp/'+code_server_bin+'.tar.gz'}}"
  become: true

- name: Changing perm of "/bin/code-server", adding "+x"
  file: dest=/bin/code-server mode=a+x
  become: true

- name: Creates directory
  file:
    path: "{{ code_server_directory}}"
    state: directory
